// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_rpc.proto

package fpga

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request containing the block struct.
type BlockRequest struct {
	BlockId              *uint64                     `protobuf:"varint,1,req,name=block_id,json=blockId" json:"block_id,omitempty"`
	ColdStart            *bool                       `protobuf:"varint,2,req,name=cold_start,json=coldStart" json:"cold_start,omitempty"`
	TxCount              *uint32                     `protobuf:"varint,3,req,name=tx_count,json=txCount" json:"tx_count,omitempty"`
	Tx                   []*BlockRequest_Transaction `protobuf:"bytes,4,rep,name=tx" json:"tx,omitempty"`
	Crc                  *uint32                     `protobuf:"varint,5,req,name=crc" json:"crc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *BlockRequest) GetColdStart() bool {
	if m != nil && m.ColdStart != nil {
		return *m.ColdStart
	}
	return false
}

func (m *BlockRequest) GetTxCount() uint32 {
	if m != nil && m.TxCount != nil {
		return *m.TxCount
	}
	return 0
}

func (m *BlockRequest) GetTx() []*BlockRequest_Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *BlockRequest) GetCrc() uint32 {
	if m != nil && m.Crc != nil {
		return *m.Crc
	}
	return 0
}

// transaction
type BlockRequest_Transaction struct {
	TxId                 *string                                     `protobuf:"bytes,1,req,name=tx_id,json=txId" json:"tx_id,omitempty"`
	RdCount              *uint32                                     `protobuf:"varint,2,req,name=rd_count,json=rdCount" json:"rd_count,omitempty"`
	WtCount              *uint32                                     `protobuf:"varint,3,req,name=wt_count,json=wtCount" json:"wt_count,omitempty"`
	SgCount              *uint32                                     `protobuf:"varint,4,req,name=sg_count,json=sgCount" json:"sg_count,omitempty"`
	DbgTxValid           *bool                                       `protobuf:"varint,5,opt,name=dbg_tx_valid,json=dbgTxValid" json:"dbg_tx_valid,omitempty"`
	Signatures           []*BlockRequest_Transaction_SignatureStruct `protobuf:"bytes,6,rep,name=signatures" json:"signatures,omitempty"`
	Reads                []*BlockRequest_Transaction_ReadStruct      `protobuf:"bytes,7,rep,name=reads" json:"reads,omitempty"`
	Writes               []*BlockRequest_Transaction_WriteStruct     `protobuf:"bytes,8,rep,name=writes" json:"writes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *BlockRequest_Transaction) Reset()         { *m = BlockRequest_Transaction{} }
func (m *BlockRequest_Transaction) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction) ProtoMessage()    {}
func (*BlockRequest_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{0, 0}
}

func (m *BlockRequest_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction.Merge(m, src)
}
func (m *BlockRequest_Transaction) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction.Size(m)
}
func (m *BlockRequest_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction proto.InternalMessageInfo

func (m *BlockRequest_Transaction) GetTxId() string {
	if m != nil && m.TxId != nil {
		return *m.TxId
	}
	return ""
}

func (m *BlockRequest_Transaction) GetRdCount() uint32 {
	if m != nil && m.RdCount != nil {
		return *m.RdCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetWtCount() uint32 {
	if m != nil && m.WtCount != nil {
		return *m.WtCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetSgCount() uint32 {
	if m != nil && m.SgCount != nil {
		return *m.SgCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetDbgTxValid() bool {
	if m != nil && m.DbgTxValid != nil {
		return *m.DbgTxValid
	}
	return false
}

func (m *BlockRequest_Transaction) GetSignatures() []*BlockRequest_Transaction_SignatureStruct {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *BlockRequest_Transaction) GetReads() []*BlockRequest_Transaction_ReadStruct {
	if m != nil {
		return m.Reads
	}
	return nil
}

func (m *BlockRequest_Transaction) GetWrites() []*BlockRequest_Transaction_WriteStruct {
	if m != nil {
		return m.Writes
	}
	return nil
}

type BlockRequest_Transaction_SignatureStruct struct {
	SignR                *string  `protobuf:"bytes,1,req,name=sign_r,json=signR" json:"sign_r,omitempty"`
	SignW                *string  `protobuf:"bytes,2,req,name=sign_w,json=signW" json:"sign_w,omitempty"`
	PkX                  *string  `protobuf:"bytes,3,req,name=pk_x,json=pkX" json:"pk_x,omitempty"`
	PkY                  *string  `protobuf:"bytes,4,req,name=pk_y,json=pkY" json:"pk_y,omitempty"`
	E                    *string  `protobuf:"bytes,5,req,name=e" json:"e,omitempty"`
	DbgSgValid           *bool    `protobuf:"varint,6,opt,name=dbg_sg_valid,json=dbgSgValid" json:"dbg_sg_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_SignatureStruct) Reset() {
	*m = BlockRequest_Transaction_SignatureStruct{}
}
func (m *BlockRequest_Transaction_SignatureStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_SignatureStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_SignatureStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{0, 0, 0}
}

func (m *BlockRequest_Transaction_SignatureStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Size(m)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_SignatureStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_SignatureStruct) GetSignR() string {
	if m != nil && m.SignR != nil {
		return *m.SignR
	}
	return ""
}

func (m *BlockRequest_Transaction_SignatureStruct) GetSignW() string {
	if m != nil && m.SignW != nil {
		return *m.SignW
	}
	return ""
}

func (m *BlockRequest_Transaction_SignatureStruct) GetPkX() string {
	if m != nil && m.PkX != nil {
		return *m.PkX
	}
	return ""
}

func (m *BlockRequest_Transaction_SignatureStruct) GetPkY() string {
	if m != nil && m.PkY != nil {
		return *m.PkY
	}
	return ""
}

func (m *BlockRequest_Transaction_SignatureStruct) GetE() string {
	if m != nil && m.E != nil {
		return *m.E
	}
	return ""
}

func (m *BlockRequest_Transaction_SignatureStruct) GetDbgSgValid() bool {
	if m != nil && m.DbgSgValid != nil {
		return *m.DbgSgValid
	}
	return false
}

type BlockRequest_Transaction_ReadStruct struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Version              *string  `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	DbgVal               *string  `protobuf:"bytes,3,opt,name=dbg_val,json=dbgVal" json:"dbg_val,omitempty"`
	DbgIsDel             *bool    `protobuf:"varint,4,opt,name=dbg_is_del,json=dbgIsDel" json:"dbg_is_del,omitempty"`
	DbgRdValid           *bool    `protobuf:"varint,5,opt,name=dbg_rd_valid,json=dbgRdValid" json:"dbg_rd_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_ReadStruct) Reset()         { *m = BlockRequest_Transaction_ReadStruct{} }
func (m *BlockRequest_Transaction_ReadStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_ReadStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_ReadStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{0, 0, 1}
}

func (m *BlockRequest_Transaction_ReadStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Size(m)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_ReadStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_ReadStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_ReadStruct) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *BlockRequest_Transaction_ReadStruct) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgVal() string {
	if m != nil && m.DbgVal != nil {
		return *m.DbgVal
	}
	return ""
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgIsDel() bool {
	if m != nil && m.DbgIsDel != nil {
		return *m.DbgIsDel
	}
	return false
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgRdValid() bool {
	if m != nil && m.DbgRdValid != nil {
		return *m.DbgRdValid
	}
	return false
}

type BlockRequest_Transaction_WriteStruct struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	IsDel                *bool    `protobuf:"varint,3,req,name=is_del,json=isDel" json:"is_del,omitempty"`
	CsVersion            *string  `protobuf:"bytes,4,opt,name=cs_version,json=csVersion" json:"cs_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_WriteStruct) Reset()         { *m = BlockRequest_Transaction_WriteStruct{} }
func (m *BlockRequest_Transaction_WriteStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_WriteStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_WriteStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{0, 0, 2}
}

func (m *BlockRequest_Transaction_WriteStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Size(m)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_WriteStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_WriteStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_WriteStruct) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *BlockRequest_Transaction_WriteStruct) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *BlockRequest_Transaction_WriteStruct) GetIsDel() bool {
	if m != nil && m.IsDel != nil {
		return *m.IsDel
	}
	return false
}

func (m *BlockRequest_Transaction_WriteStruct) GetCsVersion() string {
	if m != nil && m.CsVersion != nil {
		return *m.CsVersion
	}
	return ""
}

// The response containing the true or false Boolean value.
type BlockReply struct {
	BlockId              *uint64               `protobuf:"varint,1,req,name=block_id,json=blockId" json:"block_id,omitempty"`
	TxReplies            []*BlockReply_TXReply `protobuf:"bytes,2,rep,name=tx_replies,json=txReplies" json:"tx_replies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockReply) Reset()         { *m = BlockReply{} }
func (m *BlockReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()    {}
func (*BlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{1}
}

func (m *BlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply.Unmarshal(m, b)
}
func (m *BlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply.Marshal(b, m, deterministic)
}
func (m *BlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply.Merge(m, src)
}
func (m *BlockReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply.Size(m)
}
func (m *BlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply proto.InternalMessageInfo

func (m *BlockReply) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *BlockReply) GetTxReplies() []*BlockReply_TXReply {
	if m != nil {
		return m.TxReplies
	}
	return nil
}

// transaction
type BlockReply_TXReply struct {
	TxId                 *string                         `protobuf:"bytes,1,req,name=tx_id,json=txId" json:"tx_id,omitempty"`
	TxValid              *bool                           `protobuf:"varint,2,req,name=tx_valid,json=txValid" json:"tx_valid,omitempty"`
	SgValid              *bool                           `protobuf:"varint,3,req,name=sg_valid,json=sgValid" json:"sg_valid,omitempty"`
	RdChecks             []*BlockReply_TXReply_ReadReply `protobuf:"bytes,4,rep,name=rd_checks,json=rdChecks" json:"rd_checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BlockReply_TXReply) Reset()         { *m = BlockReply_TXReply{} }
func (m *BlockReply_TXReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply_TXReply) ProtoMessage()    {}
func (*BlockReply_TXReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{1, 0}
}

func (m *BlockReply_TXReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply_TXReply.Unmarshal(m, b)
}
func (m *BlockReply_TXReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply_TXReply.Marshal(b, m, deterministic)
}
func (m *BlockReply_TXReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply_TXReply.Merge(m, src)
}
func (m *BlockReply_TXReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply_TXReply.Size(m)
}
func (m *BlockReply_TXReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply_TXReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply_TXReply proto.InternalMessageInfo

func (m *BlockReply_TXReply) GetTxId() string {
	if m != nil && m.TxId != nil {
		return *m.TxId
	}
	return ""
}

func (m *BlockReply_TXReply) GetTxValid() bool {
	if m != nil && m.TxValid != nil {
		return *m.TxValid
	}
	return false
}

func (m *BlockReply_TXReply) GetSgValid() bool {
	if m != nil && m.SgValid != nil {
		return *m.SgValid
	}
	return false
}

func (m *BlockReply_TXReply) GetRdChecks() []*BlockReply_TXReply_ReadReply {
	if m != nil {
		return m.RdChecks
	}
	return nil
}

type BlockReply_TXReply_ReadReply struct {
	RdKey                *string  `protobuf:"bytes,1,req,name=rd_key,json=rdKey" json:"rd_key,omitempty"`
	RdValid              *bool    `protobuf:"varint,2,req,name=rd_valid,json=rdValid" json:"rd_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockReply_TXReply_ReadReply) Reset()         { *m = BlockReply_TXReply_ReadReply{} }
func (m *BlockReply_TXReply_ReadReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply_TXReply_ReadReply) ProtoMessage()    {}
func (*BlockReply_TXReply_ReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0cbfc21218ee462, []int{1, 0, 0}
}

func (m *BlockReply_TXReply_ReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Unmarshal(m, b)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Marshal(b, m, deterministic)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply_TXReply_ReadReply.Merge(m, src)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Size(m)
}
func (m *BlockReply_TXReply_ReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply_TXReply_ReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply_TXReply_ReadReply proto.InternalMessageInfo

func (m *BlockReply_TXReply_ReadReply) GetRdKey() string {
	if m != nil && m.RdKey != nil {
		return *m.RdKey
	}
	return ""
}

func (m *BlockReply_TXReply_ReadReply) GetRdValid() bool {
	if m != nil && m.RdValid != nil {
		return *m.RdValid
	}
	return false
}

func init() {
	proto.RegisterType((*BlockRequest)(nil), "protos.BlockRequest")
	proto.RegisterType((*BlockRequest_Transaction)(nil), "protos.BlockRequest.Transaction")
	proto.RegisterType((*BlockRequest_Transaction_SignatureStruct)(nil), "protos.BlockRequest.Transaction.SignatureStruct")
	proto.RegisterType((*BlockRequest_Transaction_ReadStruct)(nil), "protos.BlockRequest.Transaction.ReadStruct")
	proto.RegisterType((*BlockRequest_Transaction_WriteStruct)(nil), "protos.BlockRequest.Transaction.WriteStruct")
	proto.RegisterType((*BlockReply)(nil), "protos.BlockReply")
	proto.RegisterType((*BlockReply_TXReply)(nil), "protos.BlockReply.TXReply")
	proto.RegisterType((*BlockReply_TXReply_ReadReply)(nil), "protos.BlockReply.TXReply.ReadReply")
}

func init() { proto.RegisterFile("block_rpc.proto", fileDescriptor_f0cbfc21218ee462) }

var fileDescriptor_f0cbfc21218ee462 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0xbd, 0x92, 0xf5, 0x9c, 0x24, 0xc8, 0xbd, 0xbc, 0x29, 0xca, 0x08, 0x2d, 0x20, 0x04, 0x5d,
	0x18, 0x68, 0x61, 0x04, 0xd9, 0x15, 0x45, 0x17, 0x69, 0x02, 0x14, 0x41, 0x37, 0x01, 0x1d, 0x24,
	0xe9, 0x4a, 0x90, 0x45, 0x42, 0x15, 0x2c, 0x58, 0x2a, 0x49, 0xdb, 0xf2, 0x27, 0x74, 0xd9, 0x45,
	0xbf, 0xa4, 0xcb, 0xfe, 0x47, 0xbf, 0xa7, 0xe0, 0x43, 0x8e, 0xf3, 0x6a, 0x56, 0xd2, 0x9c, 0x21,
	0xcf, 0x1c, 0x1e, 0xce, 0x10, 0x76, 0x27, 0x75, 0x53, 0x4c, 0x33, 0xde, 0x16, 0xa3, 0x96, 0x37,
	0xb2, 0x41, 0x81, 0xfe, 0x88, 0x83, 0x9f, 0x21, 0x6c, 0x7f, 0x50, 0x39, 0xc2, 0xbe, 0xce, 0x99,
	0x90, 0x68, 0x1f, 0x22, 0xb3, 0xb6, 0xa2, 0xd8, 0x49, 0xdd, 0xa1, 0x47, 0x42, 0x1d, 0x9f, 0x51,
	0xf4, 0x12, 0xa0, 0x68, 0x6a, 0x9a, 0x09, 0x99, 0x73, 0x89, 0xdd, 0xd4, 0x1d, 0x46, 0x24, 0x56,
	0xc8, 0x58, 0x01, 0x6a, 0xa7, 0xec, 0xb2, 0xa2, 0x99, 0xcf, 0x24, 0x1e, 0xa4, 0xee, 0x70, 0x87,
	0x84, 0xb2, 0x3b, 0x51, 0x21, 0x3a, 0x04, 0x57, 0x76, 0xd8, 0x4b, 0x07, 0xc3, 0xad, 0xa3, 0xd4,
	0x28, 0x10, 0xa3, 0xcd, 0xb2, 0xa3, 0x0b, 0x9e, 0xcf, 0x44, 0x5e, 0xc8, 0xaa, 0x99, 0x11, 0x57,
	0x76, 0xe8, 0x5f, 0x18, 0x14, 0xbc, 0xc0, 0xbe, 0xe6, 0x51, 0xbf, 0xc9, 0xb7, 0x00, 0xb6, 0x36,
	0x56, 0xa1, 0xff, 0xc1, 0x97, 0x5d, 0xaf, 0x32, 0x26, 0x9e, 0xec, 0xce, 0xa8, 0xd2, 0xc0, 0xa9,
	0xd5, 0xe0, 0x1a, 0x0d, 0x9c, 0x1a, 0x0d, 0xfb, 0x10, 0x2d, 0xe5, 0x6d, 0x79, 0x4b, 0xb9, 0x4e,
	0x89, 0xd2, 0xa6, 0x3c, 0x93, 0x12, 0xa5, 0x49, 0xa5, 0xb0, 0x4d, 0x27, 0x65, 0x26, 0xbb, 0x6c,
	0x91, 0xd7, 0x15, 0xc5, 0x7e, 0xea, 0x0c, 0x23, 0x02, 0x74, 0x52, 0x5e, 0x74, 0x97, 0x0a, 0x41,
	0xe7, 0x00, 0xa2, 0x2a, 0x67, 0xb9, 0x9c, 0x73, 0x26, 0x70, 0xa0, 0xcf, 0x78, 0xf8, 0xd4, 0x19,
	0x47, 0xe3, 0x7e, 0xcb, 0x58, 0xf2, 0x79, 0x21, 0xc9, 0x06, 0x07, 0x3a, 0x06, 0x9f, 0xb3, 0x9c,
	0x0a, 0x1c, 0x6a, 0xb2, 0xd7, 0x4f, 0x92, 0x11, 0x96, 0x53, 0xcb, 0x63, 0x76, 0xa2, 0x53, 0x08,
	0x96, 0xbc, 0x92, 0x4c, 0xe0, 0x48, 0x73, 0xbc, 0x79, 0x92, 0xe3, 0x4a, 0x2d, 0xb7, 0x24, 0x76,
	0x6f, 0xf2, 0xc3, 0x81, 0xdd, 0x3b, 0x42, 0xd1, 0x33, 0x08, 0x94, 0xd4, 0x8c, 0x5b, 0xdf, 0x7d,
	0x15, 0x91, 0x35, 0xbc, 0xd4, 0xb6, 0x5b, 0xf8, 0x0a, 0xfd, 0x07, 0x5e, 0x3b, 0xcd, 0x3a, 0x6d,
	0x78, 0x4c, 0x06, 0xed, 0xf4, 0xda, 0x42, 0x2b, 0x6d, 0xb4, 0x86, 0x3e, 0xa3, 0x6d, 0x70, 0x98,
	0xbe, 0xea, 0x98, 0x38, 0xac, 0xb7, 0x5c, 0x94, 0xd6, 0xf2, 0x60, 0x6d, 0xf9, 0xb8, 0xd4, 0x96,
	0x27, 0xdf, 0x1d, 0x80, 0x9b, 0x33, 0xab, 0x5e, 0x99, 0xb2, 0x95, 0xd5, 0xa3, 0x7e, 0x11, 0x86,
	0x70, 0xc1, 0xb8, 0xa8, 0x9a, 0x99, 0x95, 0xd3, 0x87, 0xe8, 0x39, 0x84, 0x8a, 0x7c, 0x91, 0xd7,
	0x78, 0x90, 0x3a, 0xc3, 0x98, 0x04, 0x74, 0xa2, 0x58, 0xd1, 0x0b, 0x50, 0x15, 0xb2, 0x4a, 0x64,
	0x94, 0xd5, 0xd8, 0xd3, 0x35, 0x23, 0x3a, 0x29, 0xcf, 0xc4, 0x29, 0xab, 0x7b, 0x4d, 0x9c, 0xde,
	0x6b, 0x03, 0x42, 0x8d, 0xa6, 0x29, 0x6c, 0x6d, 0x58, 0xf8, 0x80, 0xa6, 0x3d, 0xf0, 0x17, 0x79,
	0x3d, 0x67, 0xbd, 0x41, 0x3a, 0x50, 0xbe, 0xd9, 0x92, 0x03, 0x3d, 0x4f, 0x7e, 0xa5, 0xeb, 0xa9,
	0x51, 0x13, 0x59, 0x7f, 0x06, 0x4f, 0x2b, 0x8d, 0x0b, 0x71, 0x69, 0x80, 0x83, 0x5f, 0x2e, 0x80,
	0xbd, 0xc9, 0xb6, 0x5e, 0xfd, 0x6d, 0x66, 0xdf, 0x02, 0xc8, 0x2e, 0xe3, 0xac, 0xad, 0x2b, 0x26,
	0xb0, 0xab, 0x9b, 0x21, 0xb9, 0xd3, 0x0c, 0x6d, 0xbd, 0x1a, 0x5d, 0x5c, 0xeb, 0x2f, 0x89, 0x65,
	0x47, 0xcc, 0xe2, 0xe4, 0xb7, 0x03, 0xa1, 0x85, 0x1f, 0x1d, 0xb6, 0xf5, 0x5c, 0x98, 0xd7, 0x20,
	0x94, 0x76, 0x28, 0xcc, 0x44, 0x99, 0x94, 0x39, 0x58, 0x28, 0xcc, 0xe5, 0xa1, 0x63, 0x88, 0xd5,
	0x88, 0x7e, 0x61, 0xc5, 0x54, 0xd8, 0x27, 0xe1, 0xd5, 0xe3, 0x82, 0x74, 0x6f, 0x1b, 0x69, 0x11,
	0xa7, 0x27, 0x7a, 0x57, 0xf2, 0x1e, 0xe2, 0x35, 0xac, 0x1c, 0xe4, 0x34, 0xbb, 0x31, 0xdb, 0xe7,
	0xf4, 0x13, 0x5b, 0xd9, 0x97, 0xe0, 0x96, 0x38, 0x6e, 0xae, 0xea, 0xe8, 0x23, 0x44, 0xa6, 0xd0,
	0xf9, 0x09, 0x7a, 0x07, 0x3b, 0x63, 0x36, 0xa3, 0x3a, 0x3e, 0xcd, 0x65, 0x8e, 0xf6, 0x1e, 0x9a,
	0x94, 0x04, 0xdd, 0x57, 0x78, 0xf0, 0xcf, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x90, 0x0f,
	0xe6, 0x56, 0x05, 0x00, 0x00,
}
