// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fpga/block_rpc.proto

package fpga

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request containing the block struct.
type BlockRequest struct {
	BlockId              uint64                      `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ColdStart            bool                        `protobuf:"varint,2,opt,name=cold_start,json=coldStart,proto3" json:"cold_start,omitempty"`
	TxCount              uint32                      `protobuf:"varint,3,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	Tx                   []*BlockRequest_Transaction `protobuf:"bytes,4,rep,name=tx,proto3" json:"tx,omitempty"`
	Crc                  uint32                      `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

func (m *BlockRequest) GetColdStart() bool {
	if m != nil {
		return m.ColdStart
	}
	return false
}

func (m *BlockRequest) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *BlockRequest) GetTx() []*BlockRequest_Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *BlockRequest) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

// transaction
type BlockRequest_Transaction struct {
	TxId                 string                                      `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	IndexInBlock         uint32                                      `protobuf:"varint,2,opt,name=indexInBlock,proto3" json:"indexInBlock,omitempty"`
	RdCount              uint32                                      `protobuf:"varint,3,opt,name=rd_count,json=rdCount,proto3" json:"rd_count,omitempty"`
	WtCount              uint32                                      `protobuf:"varint,4,opt,name=wt_count,json=wtCount,proto3" json:"wt_count,omitempty"`
	SgCount              uint32                                      `protobuf:"varint,5,opt,name=sg_count,json=sgCount,proto3" json:"sg_count,omitempty"`
	DbgTxValid           bool                                        `protobuf:"varint,6,opt,name=dbg_tx_valid,json=dbgTxValid,proto3" json:"dbg_tx_valid,omitempty"`
	Signatures           []*BlockRequest_Transaction_SignatureStruct `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Reads                []*BlockRequest_Transaction_ReadStruct      `protobuf:"bytes,8,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes               []*BlockRequest_Transaction_WriteStruct     `protobuf:"bytes,9,rep,name=writes,proto3" json:"writes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *BlockRequest_Transaction) Reset()         { *m = BlockRequest_Transaction{} }
func (m *BlockRequest_Transaction) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction) ProtoMessage()    {}
func (*BlockRequest_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{0, 0}
}

func (m *BlockRequest_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction.Merge(m, src)
}
func (m *BlockRequest_Transaction) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction.Size(m)
}
func (m *BlockRequest_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction proto.InternalMessageInfo

func (m *BlockRequest_Transaction) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *BlockRequest_Transaction) GetIndexInBlock() uint32 {
	if m != nil {
		return m.IndexInBlock
	}
	return 0
}

func (m *BlockRequest_Transaction) GetRdCount() uint32 {
	if m != nil {
		return m.RdCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetWtCount() uint32 {
	if m != nil {
		return m.WtCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetSgCount() uint32 {
	if m != nil {
		return m.SgCount
	}
	return 0
}

func (m *BlockRequest_Transaction) GetDbgTxValid() bool {
	if m != nil {
		return m.DbgTxValid
	}
	return false
}

func (m *BlockRequest_Transaction) GetSignatures() []*BlockRequest_Transaction_SignatureStruct {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *BlockRequest_Transaction) GetReads() []*BlockRequest_Transaction_ReadStruct {
	if m != nil {
		return m.Reads
	}
	return nil
}

func (m *BlockRequest_Transaction) GetWrites() []*BlockRequest_Transaction_WriteStruct {
	if m != nil {
		return m.Writes
	}
	return nil
}

type BlockRequest_Transaction_SignatureStruct struct {
	SignR                []byte   `protobuf:"bytes,1,opt,name=sign_r,json=signR,proto3" json:"sign_r,omitempty"`
	SignW                []byte   `protobuf:"bytes,2,opt,name=sign_w,json=signW,proto3" json:"sign_w,omitempty"`
	PkX                  []byte   `protobuf:"bytes,3,opt,name=pk_x,json=pkX,proto3" json:"pk_x,omitempty"`
	PkY                  []byte   `protobuf:"bytes,4,opt,name=pk_y,json=pkY,proto3" json:"pk_y,omitempty"`
	E                    []byte   `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`
	DbgSgValid           bool     `protobuf:"varint,6,opt,name=dbg_sg_valid,json=dbgSgValid,proto3" json:"dbg_sg_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_SignatureStruct) Reset() {
	*m = BlockRequest_Transaction_SignatureStruct{}
}
func (m *BlockRequest_Transaction_SignatureStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_SignatureStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_SignatureStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{0, 0, 0}
}

func (m *BlockRequest_Transaction_SignatureStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.Size(m)
}
func (m *BlockRequest_Transaction_SignatureStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_SignatureStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_SignatureStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_SignatureStruct) GetSignR() []byte {
	if m != nil {
		return m.SignR
	}
	return nil
}

func (m *BlockRequest_Transaction_SignatureStruct) GetSignW() []byte {
	if m != nil {
		return m.SignW
	}
	return nil
}

func (m *BlockRequest_Transaction_SignatureStruct) GetPkX() []byte {
	if m != nil {
		return m.PkX
	}
	return nil
}

func (m *BlockRequest_Transaction_SignatureStruct) GetPkY() []byte {
	if m != nil {
		return m.PkY
	}
	return nil
}

func (m *BlockRequest_Transaction_SignatureStruct) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *BlockRequest_Transaction_SignatureStruct) GetDbgSgValid() bool {
	if m != nil {
		return m.DbgSgValid
	}
	return false
}

type BlockRequest_Transaction_ReadStruct struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              []byte   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DbgVal               string   `protobuf:"bytes,3,opt,name=dbg_val,json=dbgVal,proto3" json:"dbg_val,omitempty"`
	DbgIsDel             bool     `protobuf:"varint,4,opt,name=dbg_is_del,json=dbgIsDel,proto3" json:"dbg_is_del,omitempty"`
	DbgRdValid           bool     `protobuf:"varint,5,opt,name=dbg_rd_valid,json=dbgRdValid,proto3" json:"dbg_rd_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_ReadStruct) Reset()         { *m = BlockRequest_Transaction_ReadStruct{} }
func (m *BlockRequest_Transaction_ReadStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_ReadStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_ReadStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{0, 0, 1}
}

func (m *BlockRequest_Transaction_ReadStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_ReadStruct.Size(m)
}
func (m *BlockRequest_Transaction_ReadStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_ReadStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_ReadStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_ReadStruct) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BlockRequest_Transaction_ReadStruct) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgVal() string {
	if m != nil {
		return m.DbgVal
	}
	return ""
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgIsDel() bool {
	if m != nil {
		return m.DbgIsDel
	}
	return false
}

func (m *BlockRequest_Transaction_ReadStruct) GetDbgRdValid() bool {
	if m != nil {
		return m.DbgRdValid
	}
	return false
}

type BlockRequest_Transaction_WriteStruct struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsDel                bool     `protobuf:"varint,3,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	CsVersion            []byte   `protobuf:"bytes,4,opt,name=cs_version,json=csVersion,proto3" json:"cs_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest_Transaction_WriteStruct) Reset()         { *m = BlockRequest_Transaction_WriteStruct{} }
func (m *BlockRequest_Transaction_WriteStruct) String() string { return proto.CompactTextString(m) }
func (*BlockRequest_Transaction_WriteStruct) ProtoMessage()    {}
func (*BlockRequest_Transaction_WriteStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{0, 0, 2}
}

func (m *BlockRequest_Transaction_WriteStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Unmarshal(m, b)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Marshal(b, m, deterministic)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Merge(m, src)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_Size() int {
	return xxx_messageInfo_BlockRequest_Transaction_WriteStruct.Size(m)
}
func (m *BlockRequest_Transaction_WriteStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest_Transaction_WriteStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest_Transaction_WriteStruct proto.InternalMessageInfo

func (m *BlockRequest_Transaction_WriteStruct) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BlockRequest_Transaction_WriteStruct) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BlockRequest_Transaction_WriteStruct) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

func (m *BlockRequest_Transaction_WriteStruct) GetCsVersion() []byte {
	if m != nil {
		return m.CsVersion
	}
	return nil
}

// The response containing the true or false Boolean value.
type BlockReply struct {
	BlockId              uint64                `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TxReplies            []*BlockReply_TXReply `protobuf:"bytes,2,rep,name=tx_replies,json=txReplies,proto3" json:"tx_replies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockReply) Reset()         { *m = BlockReply{} }
func (m *BlockReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()    {}
func (*BlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{1}
}

func (m *BlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply.Unmarshal(m, b)
}
func (m *BlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply.Marshal(b, m, deterministic)
}
func (m *BlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply.Merge(m, src)
}
func (m *BlockReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply.Size(m)
}
func (m *BlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply proto.InternalMessageInfo

func (m *BlockReply) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

func (m *BlockReply) GetTxReplies() []*BlockReply_TXReply {
	if m != nil {
		return m.TxReplies
	}
	return nil
}

// transaction
type BlockReply_TXReply struct {
	TxId                 string                          `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	IndexInBlock         uint32                          `protobuf:"varint,2,opt,name=indexInBlock,proto3" json:"indexInBlock,omitempty"`
	TxValid              bool                            `protobuf:"varint,3,opt,name=tx_valid,json=txValid,proto3" json:"tx_valid,omitempty"`
	SgValid              bool                            `protobuf:"varint,4,opt,name=sg_valid,json=sgValid,proto3" json:"sg_valid,omitempty"`
	RdChecks             []*BlockReply_TXReply_ReadReply `protobuf:"bytes,5,rep,name=rd_checks,json=rdChecks,proto3" json:"rd_checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BlockReply_TXReply) Reset()         { *m = BlockReply_TXReply{} }
func (m *BlockReply_TXReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply_TXReply) ProtoMessage()    {}
func (*BlockReply_TXReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{1, 0}
}

func (m *BlockReply_TXReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply_TXReply.Unmarshal(m, b)
}
func (m *BlockReply_TXReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply_TXReply.Marshal(b, m, deterministic)
}
func (m *BlockReply_TXReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply_TXReply.Merge(m, src)
}
func (m *BlockReply_TXReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply_TXReply.Size(m)
}
func (m *BlockReply_TXReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply_TXReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply_TXReply proto.InternalMessageInfo

func (m *BlockReply_TXReply) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *BlockReply_TXReply) GetIndexInBlock() uint32 {
	if m != nil {
		return m.IndexInBlock
	}
	return 0
}

func (m *BlockReply_TXReply) GetTxValid() bool {
	if m != nil {
		return m.TxValid
	}
	return false
}

func (m *BlockReply_TXReply) GetSgValid() bool {
	if m != nil {
		return m.SgValid
	}
	return false
}

func (m *BlockReply_TXReply) GetRdChecks() []*BlockReply_TXReply_ReadReply {
	if m != nil {
		return m.RdChecks
	}
	return nil
}

type BlockReply_TXReply_ReadReply struct {
	RdKey                string   `protobuf:"bytes,1,opt,name=rd_key,json=rdKey,proto3" json:"rd_key,omitempty"`
	RdValid              bool     `protobuf:"varint,2,opt,name=rd_valid,json=rdValid,proto3" json:"rd_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockReply_TXReply_ReadReply) Reset()         { *m = BlockReply_TXReply_ReadReply{} }
func (m *BlockReply_TXReply_ReadReply) String() string { return proto.CompactTextString(m) }
func (*BlockReply_TXReply_ReadReply) ProtoMessage()    {}
func (*BlockReply_TXReply_ReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{1, 0, 0}
}

func (m *BlockReply_TXReply_ReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Unmarshal(m, b)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Marshal(b, m, deterministic)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReply_TXReply_ReadReply.Merge(m, src)
}
func (m *BlockReply_TXReply_ReadReply) XXX_Size() int {
	return xxx_messageInfo_BlockReply_TXReply_ReadReply.Size(m)
}
func (m *BlockReply_TXReply_ReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReply_TXReply_ReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReply_TXReply_ReadReply proto.InternalMessageInfo

func (m *BlockReply_TXReply_ReadReply) GetRdKey() string {
	if m != nil {
		return m.RdKey
	}
	return ""
}

func (m *BlockReply_TXReply_ReadReply) GetRdValid() bool {
	if m != nil {
		return m.RdValid
	}
	return false
}

// *******[BEGIN] endorser sign req and resp *******
type EndorserSignRequest struct {
	SignReqs             []*SignReq `protobuf:"bytes,1,rep,name=signReqs,proto3" json:"signReqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EndorserSignRequest) Reset()         { *m = EndorserSignRequest{} }
func (m *EndorserSignRequest) String() string { return proto.CompactTextString(m) }
func (*EndorserSignRequest) ProtoMessage()    {}
func (*EndorserSignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{2}
}

func (m *EndorserSignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserSignRequest.Unmarshal(m, b)
}
func (m *EndorserSignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserSignRequest.Marshal(b, m, deterministic)
}
func (m *EndorserSignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserSignRequest.Merge(m, src)
}
func (m *EndorserSignRequest) XXX_Size() int {
	return xxx_messageInfo_EndorserSignRequest.Size(m)
}
func (m *EndorserSignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserSignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserSignRequest proto.InternalMessageInfo

func (m *EndorserSignRequest) GetSignReqs() []*SignReq {
	if m != nil {
		return m.SignReqs
	}
	return nil
}

type EndorserSignReply struct {
	SignResults          []*SignResult `protobuf:"bytes,1,rep,name=signResults,proto3" json:"signResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EndorserSignReply) Reset()         { *m = EndorserSignReply{} }
func (m *EndorserSignReply) String() string { return proto.CompactTextString(m) }
func (*EndorserSignReply) ProtoMessage()    {}
func (*EndorserSignReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{3}
}

func (m *EndorserSignReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserSignReply.Unmarshal(m, b)
}
func (m *EndorserSignReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserSignReply.Marshal(b, m, deterministic)
}
func (m *EndorserSignReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserSignReply.Merge(m, src)
}
func (m *EndorserSignReply) XXX_Size() int {
	return xxx_messageInfo_EndorserSignReply.Size(m)
}
func (m *EndorserSignReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserSignReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserSignReply proto.InternalMessageInfo

func (m *EndorserSignReply) GetSignResults() []*SignResult {
	if m != nil {
		return m.SignResults
	}
	return nil
}

// sign request
type SignReq struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	D                    []byte   `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignReq) Reset()         { *m = SignReq{} }
func (m *SignReq) String() string { return proto.CompactTextString(m) }
func (*SignReq) ProtoMessage()    {}
func (*SignReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{4}
}

func (m *SignReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignReq.Unmarshal(m, b)
}
func (m *SignReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignReq.Marshal(b, m, deterministic)
}
func (m *SignReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignReq.Merge(m, src)
}
func (m *SignReq) XXX_Size() int {
	return xxx_messageInfo_SignReq.Size(m)
}
func (m *SignReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignReq proto.InternalMessageInfo

func (m *SignReq) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *SignReq) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *SignReq) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// signature response
type SignResult struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	SignR                []byte   `protobuf:"bytes,2,opt,name=sign_r,json=signR,proto3" json:"sign_r,omitempty"`
	SignS                []byte   `protobuf:"bytes,3,opt,name=sign_s,json=signS,proto3" json:"sign_s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignResult) Reset()         { *m = SignResult{} }
func (m *SignResult) String() string { return proto.CompactTextString(m) }
func (*SignResult) ProtoMessage()    {}
func (*SignResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{5}
}

func (m *SignResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResult.Unmarshal(m, b)
}
func (m *SignResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResult.Marshal(b, m, deterministic)
}
func (m *SignResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResult.Merge(m, src)
}
func (m *SignResult) XXX_Size() int {
	return xxx_messageInfo_SignResult.Size(m)
}
func (m *SignResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResult.DiscardUnknown(m)
}

var xxx_messageInfo_SignResult proto.InternalMessageInfo

func (m *SignResult) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *SignResult) GetSignR() []byte {
	if m != nil {
		return m.SignR
	}
	return nil
}

func (m *SignResult) GetSignS() []byte {
	if m != nil {
		return m.SignS
	}
	return nil
}

// *******[BEGIN] endorser verify req and resp *******
type EndorserVerifyRequest struct {
	VerifyReqs           []*VerifyReq `protobuf:"bytes,1,rep,name=verifyReqs,proto3" json:"verifyReqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EndorserVerifyRequest) Reset()         { *m = EndorserVerifyRequest{} }
func (m *EndorserVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*EndorserVerifyRequest) ProtoMessage()    {}
func (*EndorserVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{6}
}

func (m *EndorserVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserVerifyRequest.Unmarshal(m, b)
}
func (m *EndorserVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserVerifyRequest.Marshal(b, m, deterministic)
}
func (m *EndorserVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserVerifyRequest.Merge(m, src)
}
func (m *EndorserVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_EndorserVerifyRequest.Size(m)
}
func (m *EndorserVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserVerifyRequest proto.InternalMessageInfo

func (m *EndorserVerifyRequest) GetVerifyReqs() []*VerifyReq {
	if m != nil {
		return m.VerifyReqs
	}
	return nil
}

type EndorserVerifyReply struct {
	VerifyResults        []*VerifyResult `protobuf:"bytes,1,rep,name=verifyResults,proto3" json:"verifyResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EndorserVerifyReply) Reset()         { *m = EndorserVerifyReply{} }
func (m *EndorserVerifyReply) String() string { return proto.CompactTextString(m) }
func (*EndorserVerifyReply) ProtoMessage()    {}
func (*EndorserVerifyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{7}
}

func (m *EndorserVerifyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorserVerifyReply.Unmarshal(m, b)
}
func (m *EndorserVerifyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorserVerifyReply.Marshal(b, m, deterministic)
}
func (m *EndorserVerifyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorserVerifyReply.Merge(m, src)
}
func (m *EndorserVerifyReply) XXX_Size() int {
	return xxx_messageInfo_EndorserVerifyReply.Size(m)
}
func (m *EndorserVerifyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorserVerifyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndorserVerifyReply proto.InternalMessageInfo

func (m *EndorserVerifyReply) GetVerifyResults() []*VerifyResult {
	if m != nil {
		return m.VerifyResults
	}
	return nil
}

type VerifyReq struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	SignR                []byte   `protobuf:"bytes,2,opt,name=sign_r,json=signR,proto3" json:"sign_r,omitempty"`
	SignS                []byte   `protobuf:"bytes,3,opt,name=sign_s,json=signS,proto3" json:"sign_s,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Px                   []byte   `protobuf:"bytes,5,opt,name=px,proto3" json:"px,omitempty"`
	Py                   []byte   `protobuf:"bytes,6,opt,name=py,proto3" json:"py,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{8}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *VerifyReq) GetSignR() []byte {
	if m != nil {
		return m.SignR
	}
	return nil
}

func (m *VerifyReq) GetSignS() []byte {
	if m != nil {
		return m.SignS
	}
	return nil
}

func (m *VerifyReq) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *VerifyReq) GetPx() []byte {
	if m != nil {
		return m.Px
	}
	return nil
}

func (m *VerifyReq) GetPy() []byte {
	if m != nil {
		return m.Py
	}
	return nil
}

type VerifyResult struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResult) Reset()         { *m = VerifyResult{} }
func (m *VerifyResult) String() string { return proto.CompactTextString(m) }
func (*VerifyResult) ProtoMessage()    {}
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_307fe3136a2eb14d, []int{9}
}

func (m *VerifyResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResult.Unmarshal(m, b)
}
func (m *VerifyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResult.Marshal(b, m, deterministic)
}
func (m *VerifyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResult.Merge(m, src)
}
func (m *VerifyResult) XXX_Size() int {
	return xxx_messageInfo_VerifyResult.Size(m)
}
func (m *VerifyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResult proto.InternalMessageInfo

func (m *VerifyResult) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *VerifyResult) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*BlockRequest)(nil), "fpga.BlockRequest")
	proto.RegisterType((*BlockRequest_Transaction)(nil), "fpga.BlockRequest.Transaction")
	proto.RegisterType((*BlockRequest_Transaction_SignatureStruct)(nil), "fpga.BlockRequest.Transaction.SignatureStruct")
	proto.RegisterType((*BlockRequest_Transaction_ReadStruct)(nil), "fpga.BlockRequest.Transaction.ReadStruct")
	proto.RegisterType((*BlockRequest_Transaction_WriteStruct)(nil), "fpga.BlockRequest.Transaction.WriteStruct")
	proto.RegisterType((*BlockReply)(nil), "fpga.BlockReply")
	proto.RegisterType((*BlockReply_TXReply)(nil), "fpga.BlockReply.TXReply")
	proto.RegisterType((*BlockReply_TXReply_ReadReply)(nil), "fpga.BlockReply.TXReply.ReadReply")
	proto.RegisterType((*EndorserSignRequest)(nil), "fpga.EndorserSignRequest")
	proto.RegisterType((*EndorserSignReply)(nil), "fpga.EndorserSignReply")
	proto.RegisterType((*SignReq)(nil), "fpga.SignReq")
	proto.RegisterType((*SignResult)(nil), "fpga.SignResult")
	proto.RegisterType((*EndorserVerifyRequest)(nil), "fpga.EndorserVerifyRequest")
	proto.RegisterType((*EndorserVerifyReply)(nil), "fpga.EndorserVerifyReply")
	proto.RegisterType((*VerifyReq)(nil), "fpga.VerifyReq")
	proto.RegisterType((*VerifyResult)(nil), "fpga.VerifyResult")
}

func init() { proto.RegisterFile("fpga/block_rpc.proto", fileDescriptor_307fe3136a2eb14d) }

var fileDescriptor_307fe3136a2eb14d = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x2d, 0x25, 0x51, 0x24, 0xaf, 0xa9, 0xc4, 0x99, 0x24, 0x08, 0xad, 0x3e, 0x20, 0x70, 0xe5,
	0x74, 0xa1, 0x00, 0xee, 0x22, 0x05, 0x8a, 0x22, 0x85, 0xed, 0xa2, 0x55, 0x0b, 0xf4, 0x31, 0x32,
	0x9c, 0x74, 0x45, 0x50, 0x9c, 0x09, 0x4d, 0x88, 0xa0, 0xe8, 0x99, 0x91, 0x44, 0xed, 0xfb, 0x03,
	0x5d, 0xf4, 0x1b, 0xfa, 0x39, 0x5d, 0x75, 0xd5, 0x1f, 0xe9, 0xb2, 0x98, 0x07, 0x29, 0x32, 0x91,
	0x93, 0x45, 0xbb, 0x12, 0xef, 0x63, 0xce, 0x9c, 0x7b, 0xee, 0xbd, 0x03, 0xc1, 0xa3, 0xd7, 0x65,
	0x1a, 0x3f, 0x5b, 0xe4, 0xab, 0x64, 0x19, 0xb1, 0x32, 0x99, 0x96, 0x6c, 0x25, 0x56, 0x68, 0x20,
	0xbd, 0xe1, 0x9f, 0x0e, 0xf8, 0xe7, 0x32, 0x82, 0xe9, 0xed, 0x9a, 0x72, 0x81, 0x4e, 0xc0, 0xd5,
	0x99, 0x19, 0x09, 0xac, 0x89, 0x75, 0x3a, 0xc0, 0x8e, 0xb2, 0x67, 0x04, 0x7d, 0x0c, 0x90, 0xac,
	0x72, 0x12, 0x71, 0x11, 0x33, 0x11, 0xf4, 0x26, 0xd6, 0xa9, 0x8b, 0x3d, 0xe9, 0x99, 0x4b, 0x87,
	0x3c, 0x29, 0xaa, 0x28, 0x59, 0xad, 0x0b, 0x11, 0xf4, 0x27, 0xd6, 0xe9, 0x08, 0x3b, 0xa2, 0xba,
	0x90, 0x26, 0x9a, 0x42, 0x4f, 0x54, 0xc1, 0x60, 0xd2, 0x3f, 0x3d, 0x3a, 0xfb, 0x64, 0x2a, 0x2f,
	0x9e, 0xb6, 0x2f, 0x9d, 0x5e, 0xb1, 0xb8, 0xe0, 0x71, 0x22, 0xb2, 0x55, 0x81, 0x7b, 0xa2, 0x42,
	0xc7, 0xd0, 0x4f, 0x58, 0x12, 0xd8, 0x0a, 0x45, 0x7e, 0x8e, 0xff, 0x18, 0xc2, 0x51, 0x2b, 0x0b,
	0x3d, 0x04, 0x5b, 0x54, 0x35, 0x47, 0x0f, 0x0f, 0x44, 0x35, 0x23, 0x28, 0x04, 0x3f, 0x2b, 0x08,
	0xad, 0x66, 0x85, 0x42, 0x57, 0x14, 0x47, 0xb8, 0xe3, 0x93, 0x2c, 0x19, 0xe9, 0xb2, 0x64, 0x44,
	0xb3, 0x3c, 0x01, 0x77, 0x2b, 0x4c, 0x68, 0xa0, 0x43, 0x5b, 0xd1, 0x84, 0x78, 0x6a, 0x42, 0x9a,
	0x95, 0xc3, 0x53, 0x1d, 0x9a, 0x80, 0x4f, 0x16, 0x69, 0x24, 0xaa, 0x68, 0x13, 0xe7, 0x19, 0x09,
	0x86, 0x4a, 0x17, 0x20, 0x8b, 0xf4, 0xaa, 0xba, 0x96, 0x1e, 0xf4, 0x03, 0x00, 0xcf, 0xd2, 0x22,
	0x16, 0x6b, 0x46, 0x79, 0xe0, 0x28, 0x15, 0xa6, 0xef, 0x56, 0x61, 0x3a, 0xaf, 0x0f, 0xcc, 0x05,
	0x5b, 0x27, 0x02, 0xb7, 0x10, 0xd0, 0x0b, 0xb0, 0x19, 0x8d, 0x09, 0x0f, 0x5c, 0x05, 0xf5, 0xf4,
	0x3d, 0x50, 0x98, 0xc6, 0xc4, 0xa0, 0xe8, 0x73, 0xe8, 0x1c, 0x86, 0x5b, 0x96, 0x09, 0xca, 0x03,
	0x4f, 0x21, 0x7c, 0xfa, 0x1e, 0x84, 0x97, 0x32, 0xd9, 0x40, 0x98, 0x93, 0xe3, 0xdf, 0x2d, 0xb8,
	0xff, 0x06, 0x49, 0xf4, 0x18, 0x86, 0x92, 0x66, 0xc4, 0x54, 0x57, 0x7c, 0x6c, 0x4b, 0x0b, 0x37,
	0xee, 0xad, 0x6a, 0x88, 0x71, 0xbf, 0x44, 0x0f, 0x60, 0x50, 0x2e, 0xa3, 0x4a, 0x75, 0xc1, 0xc7,
	0xfd, 0x72, 0xf9, 0xca, 0xb8, 0x76, 0x4a, 0x7d, 0xe5, 0xfa, 0x05, 0xf9, 0x60, 0x51, 0x25, 0xb9,
	0x8f, 0x2d, 0x5a, 0x8b, 0xcd, 0xd3, 0xb7, 0xc4, 0x9e, 0xa7, 0x4a, 0xec, 0xf1, 0x6f, 0x16, 0xc0,
	0xbe, 0x62, 0x39, 0x49, 0x4b, 0xba, 0x33, 0x53, 0x22, 0x3f, 0x51, 0x00, 0xce, 0x86, 0x32, 0x9e,
	0xad, 0x0a, 0x43, 0xa7, 0x36, 0xd1, 0x13, 0x70, 0x24, 0xf8, 0x26, 0xce, 0x15, 0x27, 0x0f, 0x0f,
	0xc9, 0x42, 0xa2, 0xa2, 0x8f, 0x40, 0xde, 0x10, 0x65, 0x3c, 0x22, 0x34, 0x57, 0xe4, 0x5c, 0xec,
	0x92, 0x45, 0x3a, 0xe3, 0x97, 0x34, 0xaf, 0x39, 0x31, 0x62, 0x38, 0xd9, 0x0d, 0x27, 0x4c, 0x34,
	0xa7, 0x25, 0x1c, 0xb5, 0x24, 0x3c, 0xc0, 0xe9, 0x11, 0xd8, 0x9b, 0x38, 0x5f, 0xd3, 0x5a, 0x20,
	0x65, 0x48, 0xdd, 0xcc, 0x95, 0x7d, 0x05, 0x69, 0x67, 0xea, 0x3e, 0xb9, 0x86, 0x3c, 0xaa, 0x6b,
	0xd0, 0x52, 0x79, 0x09, 0xbf, 0xd6, 0x8e, 0xf0, 0xef, 0x1e, 0x80, 0xe9, 0x64, 0x99, 0xef, 0xde,
	0xb5, 0xcf, 0xcf, 0x01, 0x44, 0x15, 0x31, 0x5a, 0xe6, 0x19, 0xe5, 0x41, 0x4f, 0x8d, 0x42, 0xd0,
	0x19, 0x85, 0x32, 0xdf, 0x4d, 0xaf, 0x5e, 0xa9, 0x5f, 0xec, 0x89, 0x0a, 0xeb, 0xd4, 0xf1, 0x3f,
	0x16, 0x38, 0xc6, 0xfd, 0x9f, 0x16, 0xb1, 0xd9, 0x19, 0x5d, 0x9f, 0x23, 0xcc, 0xc2, 0xe8, 0x6d,
	0xd3, 0x21, 0xad, 0xb6, 0xc3, 0x75, 0x7b, 0xd1, 0x0b, 0xf0, 0xe4, 0xfa, 0xde, 0xd0, 0x64, 0xc9,
	0x03, 0x5b, 0x51, 0x0e, 0xef, 0xa2, 0xac, 0x26, 0x5f, 0x93, 0x77, 0x19, 0xb9, 0x50, 0x67, 0xc6,
	0x5f, 0x82, 0xd7, 0xb8, 0xa5, 0xc2, 0x8c, 0x44, 0xfb, 0x66, 0xd8, 0x8c, 0x7c, 0x4f, 0x77, 0xe6,
	0x8d, 0xd0, 0xf7, 0xeb, 0x67, 0xce, 0x61, 0xba, 0x95, 0xe1, 0x57, 0xf0, 0xf0, 0xeb, 0x82, 0xac,
	0x18, 0xa7, 0x4c, 0x4e, 0x7f, 0xfd, 0x6a, 0x3e, 0x05, 0x97, 0x6b, 0x93, 0x07, 0x96, 0x62, 0x35,
	0xd2, 0xac, 0x4c, 0x12, 0x6e, 0xc2, 0xe1, 0x37, 0xf0, 0xa0, 0x8b, 0x20, 0x89, 0x9c, 0xc1, 0x91,
	0x4e, 0xe0, 0xeb, 0x5c, 0xd4, 0x10, 0xc7, 0x6d, 0x08, 0x19, 0xc0, 0xed, 0xa4, 0xf0, 0x1c, 0x1c,
	0x83, 0xae, 0xea, 0xa0, 0xb7, 0x75, 0x17, 0x6c, 0xb9, 0xe7, 0xb7, 0x33, 0x22, 0x77, 0x87, 0x98,
	0x91, 0xb2, 0x08, 0x42, 0x30, 0xb8, 0x89, 0xf9, 0x8d, 0xd9, 0x37, 0xf5, 0x1d, 0xfe, 0x0c, 0xb0,
	0x87, 0xbf, 0x0b, 0x66, 0xbf, 0xd6, 0xbd, 0x43, 0x6b, 0xcd, 0x0d, 0xa2, 0x72, 0xcf, 0xc3, 0x6f,
	0xe1, 0x71, 0x5d, 0xdf, 0x35, 0x65, 0xd9, 0xeb, 0x5d, 0xad, 0xd1, 0x33, 0x80, 0x4d, 0xed, 0xa8,
	0x4b, 0xbc, 0xaf, 0x4b, 0x6c, 0x12, 0x71, 0x2b, 0x25, 0xfc, 0x71, 0xaf, 0x75, 0x9d, 0x20, 0xb5,
	0xfa, 0x1c, 0x46, 0x75, 0x52, 0x5b, 0x2d, 0xd4, 0x85, 0x52, 0x7a, 0x75, 0x13, 0xc3, 0x5f, 0x2d,
	0xf0, 0x9a, 0xab, 0xfe, 0x97, 0x6a, 0x1b, 0x51, 0x07, 0x7b, 0x51, 0xd1, 0x3d, 0xe8, 0x95, 0x95,
	0x79, 0xb3, 0x7a, 0x65, 0xa5, 0xec, 0x9d, 0x7a, 0xaa, 0xa4, 0xbd, 0x0b, 0xbf, 0x00, 0xbf, 0xcd,
	0xf2, 0x2e, 0x22, 0xfa, 0x51, 0x68, 0x46, 0x50, 0x1b, 0x67, 0x7f, 0x59, 0xe0, 0xea, 0x51, 0xff,
	0xe9, 0x02, 0x3d, 0x87, 0xd1, 0x9c, 0x16, 0x44, 0xd9, 0x97, 0xb1, 0x88, 0x11, 0x7a, 0xfb, 0x25,
	0x1f, 0x1f, 0xbf, 0xb9, 0x1f, 0xe1, 0x07, 0xe8, 0x12, 0xfc, 0xf6, 0x10, 0xa2, 0x13, 0x9d, 0x73,
	0x60, 0xb4, 0xc7, 0x4f, 0x0e, 0x85, 0x34, 0xca, 0x77, 0x70, 0xaf, 0xdb, 0x20, 0xf4, 0x61, 0x37,
	0xb9, 0x33, 0x00, 0xe3, 0x93, 0xc3, 0x41, 0x85, 0xb5, 0x18, 0xaa, 0x7f, 0x25, 0x9f, 0xfd, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xec, 0xd6, 0x42, 0x85, 0xad, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockRPCClient is the client API for BlockRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockRPCClient interface {
	// Sends a block (vscc in block commitment vscc
	SendBlockData(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error)
	// endorse sign & verify
	EndorserSign(ctx context.Context, in *EndorserSignRequest, opts ...grpc.CallOption) (*EndorserSignReply, error)
	EndorserVerify(ctx context.Context, in *EndorserVerifyRequest, opts ...grpc.CallOption) (*EndorserVerifyReply, error)
}

type blockRPCClient struct {
	cc *grpc.ClientConn
}

func NewBlockRPCClient(cc *grpc.ClientConn) BlockRPCClient {
	return &blockRPCClient{cc}
}

func (c *blockRPCClient) SendBlockData(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error) {
	out := new(BlockReply)
	err := c.cc.Invoke(ctx, "/fpga.BlockRPC/SendBlockData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockRPCClient) EndorserSign(ctx context.Context, in *EndorserSignRequest, opts ...grpc.CallOption) (*EndorserSignReply, error) {
	out := new(EndorserSignReply)
	err := c.cc.Invoke(ctx, "/fpga.BlockRPC/EndorserSign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockRPCClient) EndorserVerify(ctx context.Context, in *EndorserVerifyRequest, opts ...grpc.CallOption) (*EndorserVerifyReply, error) {
	out := new(EndorserVerifyReply)
	err := c.cc.Invoke(ctx, "/fpga.BlockRPC/EndorserVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockRPCServer is the server API for BlockRPC service.
type BlockRPCServer interface {
	// Sends a block (vscc in block commitment vscc
	SendBlockData(context.Context, *BlockRequest) (*BlockReply, error)
	// endorse sign & verify
	EndorserSign(context.Context, *EndorserSignRequest) (*EndorserSignReply, error)
	EndorserVerify(context.Context, *EndorserVerifyRequest) (*EndorserVerifyReply, error)
}

func RegisterBlockRPCServer(s *grpc.Server, srv BlockRPCServer) {
	s.RegisterService(&_BlockRPC_serviceDesc, srv)
}

func _BlockRPC_SendBlockData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).SendBlockData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpga.BlockRPC/SendBlockData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).SendBlockData(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockRPC_EndorserSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorserSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).EndorserSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpga.BlockRPC/EndorserSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).EndorserSign(ctx, req.(*EndorserSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockRPC_EndorserVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorserVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).EndorserVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpga.BlockRPC/EndorserVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).EndorserVerify(ctx, req.(*EndorserVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fpga.BlockRPC",
	HandlerType: (*BlockRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBlockData",
			Handler:    _BlockRPC_SendBlockData_Handler,
		},
		{
			MethodName: "EndorserSign",
			Handler:    _BlockRPC_EndorserSign_Handler,
		},
		{
			MethodName: "EndorserVerify",
			Handler:    _BlockRPC_EndorserVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fpga/block_rpc.proto",
}
