// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fpga/fpga.proto

package fpga

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	kvrwset "github.com/hyperledger/fabric/protos/ledger/rwset/kvrwset"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VsccEnvelope struct {
	SignR                []byte   `protobuf:"bytes,1,opt,name=sign_r,json=signR,proto3" json:"sign_r,omitempty"`
	SignS                []byte   `protobuf:"bytes,2,opt,name=sign_s,json=signS,proto3" json:"sign_s,omitempty"`
	PkX                  []byte   `protobuf:"bytes,3,opt,name=pk_x,json=pkX,proto3" json:"pk_x,omitempty"`
	PkY                  []byte   `protobuf:"bytes,4,opt,name=pk_y,json=pkY,proto3" json:"pk_y,omitempty"`
	E                    []byte   `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VsccEnvelope) Reset()         { *m = VsccEnvelope{} }
func (m *VsccEnvelope) String() string { return proto.CompactTextString(m) }
func (*VsccEnvelope) ProtoMessage()    {}
func (*VsccEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{0}
}

func (m *VsccEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VsccEnvelope.Unmarshal(m, b)
}
func (m *VsccEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VsccEnvelope.Marshal(b, m, deterministic)
}
func (m *VsccEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VsccEnvelope.Merge(m, src)
}
func (m *VsccEnvelope) XXX_Size() int {
	return xxx_messageInfo_VsccEnvelope.Size(m)
}
func (m *VsccEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_VsccEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_VsccEnvelope proto.InternalMessageInfo

func (m *VsccEnvelope) GetSignR() []byte {
	if m != nil {
		return m.SignR
	}
	return nil
}

func (m *VsccEnvelope) GetSignS() []byte {
	if m != nil {
		return m.SignS
	}
	return nil
}

func (m *VsccEnvelope) GetPkX() []byte {
	if m != nil {
		return m.PkX
	}
	return nil
}

func (m *VsccEnvelope) GetPkY() []byte {
	if m != nil {
		return m.PkY
	}
	return nil
}

func (m *VsccEnvelope) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

type VsccResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VsccResponse) Reset()         { *m = VsccResponse{} }
func (m *VsccResponse) String() string { return proto.CompactTextString(m) }
func (*VsccResponse) ProtoMessage()    {}
func (*VsccResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{1}
}

func (m *VsccResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VsccResponse.Unmarshal(m, b)
}
func (m *VsccResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VsccResponse.Marshal(b, m, deterministic)
}
func (m *VsccResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VsccResponse.Merge(m, src)
}
func (m *VsccResponse) XXX_Size() int {
	return xxx_messageInfo_VsccResponse.Size(m)
}
func (m *VsccResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VsccResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VsccResponse proto.InternalMessageInfo

func (m *VsccResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type Block4Mvcc struct {
	Num                  uint64              `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Txs                  []*Transaction4Mvcc `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block4Mvcc) Reset()         { *m = Block4Mvcc{} }
func (m *Block4Mvcc) String() string { return proto.CompactTextString(m) }
func (*Block4Mvcc) ProtoMessage()    {}
func (*Block4Mvcc) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{2}
}

func (m *Block4Mvcc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block4Mvcc.Unmarshal(m, b)
}
func (m *Block4Mvcc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block4Mvcc.Marshal(b, m, deterministic)
}
func (m *Block4Mvcc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block4Mvcc.Merge(m, src)
}
func (m *Block4Mvcc) XXX_Size() int {
	return xxx_messageInfo_Block4Mvcc.Size(m)
}
func (m *Block4Mvcc) XXX_DiscardUnknown() {
	xxx_messageInfo_Block4Mvcc.DiscardUnknown(m)
}

var xxx_messageInfo_Block4Mvcc proto.InternalMessageInfo

func (m *Block4Mvcc) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Block4Mvcc) GetTxs() []*Transaction4Mvcc {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Transaction4Mvcc struct {
	IndexInBlock         int32    `protobuf:"varint,1,opt,name=index_in_block,json=indexInBlock,proto3" json:"index_in_block,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RdCount              uint32   `protobuf:"varint,3,opt,name=rd_count,json=rdCount,proto3" json:"rd_count,omitempty"`
	WtCount              uint32   `protobuf:"varint,4,opt,name=wt_count,json=wtCount,proto3" json:"wt_count,omitempty"`
	Rs                   []*TxRS  `protobuf:"bytes,5,rep,name=rs,proto3" json:"rs,omitempty"`
	Ws                   []*TxWS  `protobuf:"bytes,6,rep,name=ws,proto3" json:"ws,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction4Mvcc) Reset()         { *m = Transaction4Mvcc{} }
func (m *Transaction4Mvcc) String() string { return proto.CompactTextString(m) }
func (*Transaction4Mvcc) ProtoMessage()    {}
func (*Transaction4Mvcc) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{3}
}

func (m *Transaction4Mvcc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction4Mvcc.Unmarshal(m, b)
}
func (m *Transaction4Mvcc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction4Mvcc.Marshal(b, m, deterministic)
}
func (m *Transaction4Mvcc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction4Mvcc.Merge(m, src)
}
func (m *Transaction4Mvcc) XXX_Size() int {
	return xxx_messageInfo_Transaction4Mvcc.Size(m)
}
func (m *Transaction4Mvcc) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction4Mvcc.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction4Mvcc proto.InternalMessageInfo

func (m *Transaction4Mvcc) GetIndexInBlock() int32 {
	if m != nil {
		return m.IndexInBlock
	}
	return 0
}

func (m *Transaction4Mvcc) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction4Mvcc) GetRdCount() uint32 {
	if m != nil {
		return m.RdCount
	}
	return 0
}

func (m *Transaction4Mvcc) GetWtCount() uint32 {
	if m != nil {
		return m.WtCount
	}
	return 0
}

func (m *Transaction4Mvcc) GetRs() []*TxRS {
	if m != nil {
		return m.Rs
	}
	return nil
}

func (m *Transaction4Mvcc) GetWs() []*TxWS {
	if m != nil {
		return m.Ws
	}
	return nil
}

type TxRS struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              *kvrwset.Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TxRS) Reset()         { *m = TxRS{} }
func (m *TxRS) String() string { return proto.CompactTextString(m) }
func (*TxRS) ProtoMessage()    {}
func (*TxRS) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{4}
}

func (m *TxRS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRS.Unmarshal(m, b)
}
func (m *TxRS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRS.Marshal(b, m, deterministic)
}
func (m *TxRS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRS.Merge(m, src)
}
func (m *TxRS) XXX_Size() int {
	return xxx_messageInfo_TxRS.Size(m)
}
func (m *TxRS) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRS.DiscardUnknown(m)
}

var xxx_messageInfo_TxRS proto.InternalMessageInfo

func (m *TxRS) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TxRS) GetVersion() *kvrwset.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type TxWS struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsDel                bool     `protobuf:"varint,3,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxWS) Reset()         { *m = TxWS{} }
func (m *TxWS) String() string { return proto.CompactTextString(m) }
func (*TxWS) ProtoMessage()    {}
func (*TxWS) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{5}
}

func (m *TxWS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxWS.Unmarshal(m, b)
}
func (m *TxWS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxWS.Marshal(b, m, deterministic)
}
func (m *TxWS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxWS.Merge(m, src)
}
func (m *TxWS) XXX_Size() int {
	return xxx_messageInfo_TxWS.Size(m)
}
func (m *TxWS) XXX_DiscardUnknown() {
	xxx_messageInfo_TxWS.DiscardUnknown(m)
}

var xxx_messageInfo_TxWS proto.InternalMessageInfo

func (m *TxWS) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TxWS) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TxWS) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

type MvccResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MvccResponse) Reset()         { *m = MvccResponse{} }
func (m *MvccResponse) String() string { return proto.CompactTextString(m) }
func (*MvccResponse) ProtoMessage()    {}
func (*MvccResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_715153acf2a30ae8, []int{6}
}

func (m *MvccResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MvccResponse.Unmarshal(m, b)
}
func (m *MvccResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MvccResponse.Marshal(b, m, deterministic)
}
func (m *MvccResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MvccResponse.Merge(m, src)
}
func (m *MvccResponse) XXX_Size() int {
	return xxx_messageInfo_MvccResponse.Size(m)
}
func (m *MvccResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MvccResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MvccResponse proto.InternalMessageInfo

func (m *MvccResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*VsccEnvelope)(nil), "protos.VsccEnvelope")
	proto.RegisterType((*VsccResponse)(nil), "protos.VsccResponse")
	proto.RegisterType((*Block4Mvcc)(nil), "protos.Block4mvcc")
	proto.RegisterType((*Transaction4Mvcc)(nil), "protos.Transaction4mvcc")
	proto.RegisterType((*TxRS)(nil), "protos.TxRS")
	proto.RegisterType((*TxWS)(nil), "protos.TxWS")
	proto.RegisterType((*MvccResponse)(nil), "protos.MvccResponse")
}

func init() { proto.RegisterFile("fpga/fpga.proto", fileDescriptor_715153acf2a30ae8) }

var fileDescriptor_715153acf2a30ae8 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0xd2, 0xa4, 0xeb, 0xde, 0x42, 0x29, 0xd6, 0x40, 0x61, 0xe2, 0x80, 0x02, 0x42, 0x63,
	0x48, 0x89, 0x54, 0x76, 0x44, 0x1c, 0xc6, 0x86, 0x04, 0x12, 0x17, 0x07, 0x75, 0xc0, 0x25, 0x4a,
	0x1d, 0x37, 0xb3, 0x92, 0x3a, 0x91, 0x9d, 0x1f, 0xed, 0x9d, 0xbf, 0x8a, 0xbf, 0x0e, 0xd9, 0x49,
	0xd6, 0x32, 0x21, 0xed, 0x12, 0xfb, 0x7d, 0xdf, 0xe7, 0xf7, 0xbe, 0x97, 0x67, 0xc3, 0xe3, 0x55,
	0x99, 0xc6, 0x81, 0xfa, 0xf8, 0xa5, 0x28, 0xaa, 0x02, 0x8d, 0xf5, 0x22, 0x4f, 0x5f, 0xe5, 0x34,
	0x49, 0xa9, 0x08, 0x44, 0x2b, 0x69, 0x15, 0x64, 0xcd, 0xb0, 0x46, 0x7a, 0xd3, 0x89, 0xbd, 0x12,
	0x9c, 0x85, 0x24, 0xe4, 0x9a, 0x37, 0x34, 0x2f, 0x4a, 0x8a, 0x9e, 0xc2, 0x58, 0xb2, 0x94, 0x47,
	0xc2, 0x35, 0x5e, 0x1a, 0x67, 0x0e, 0xb6, 0x55, 0x84, 0xef, 0x60, 0xe9, 0x9a, 0x3b, 0x38, 0x44,
	0x4f, 0xc0, 0x2a, 0xb3, 0x68, 0xe3, 0x8e, 0x34, 0x38, 0x2a, 0xb3, 0x1f, 0x3d, 0xb4, 0x75, 0xad,
	0x01, 0xfa, 0x89, 0x1c, 0x30, 0xa8, 0x6b, 0xeb, 0xd8, 0xa0, 0xde, 0x9b, 0xae, 0x22, 0xa6, 0xb2,
	0x2c, 0xb8, 0xa4, 0xe8, 0x19, 0x8c, 0x05, 0x95, 0x75, 0x5e, 0xe9, 0x8a, 0x13, 0xdc, 0x47, 0xde,
	0x57, 0x80, 0xcb, 0xbc, 0x20, 0xd9, 0xc5, 0xba, 0x21, 0x04, 0xcd, 0x60, 0xc4, 0xeb, 0xb5, 0x96,
	0x58, 0x58, 0x6d, 0xd1, 0x39, 0x8c, 0xaa, 0x8d, 0xf2, 0x33, 0x3a, 0x3b, 0x9e, 0xbb, 0x5d, 0x3b,
	0xd2, 0xff, 0x2e, 0x62, 0x2e, 0x63, 0x52, 0xb1, 0x82, 0xeb, 0x83, 0x58, 0x89, 0xbc, 0x3f, 0x06,
	0xcc, 0xee, 0x33, 0xe8, 0x35, 0x4c, 0x19, 0x4f, 0xe8, 0x26, 0x62, 0x3c, 0x5a, 0xaa, 0x4a, 0x3a,
	0xbb, 0x8d, 0x1d, 0x8d, 0x7e, 0xe1, 0xba, 0x3a, 0x9a, 0x82, 0xc9, 0x12, 0xdd, 0xf5, 0x11, 0x36,
	0x59, 0x82, 0x9e, 0xc3, 0x44, 0x24, 0x11, 0x29, 0x6a, 0x5e, 0xe9, 0xb6, 0x1f, 0xe1, 0x43, 0x91,
	0x7c, 0x52, 0xa1, 0xa2, 0xda, 0xaa, 0xa7, 0xac, 0x8e, 0x6a, 0xab, 0x8e, 0x7a, 0x01, 0xa6, 0x90,
	0xae, 0xad, 0xbd, 0x3a, 0x77, 0x5e, 0x37, 0x38, 0xc4, 0xa6, 0x90, 0x8a, 0x6d, 0xa5, 0x3b, 0xbe,
	0xcf, 0xde, 0x84, 0xd8, 0x6c, 0xa5, 0x77, 0x05, 0x96, 0x52, 0xaa, 0x5f, 0x90, 0xd1, 0xad, 0x36,
	0x79, 0x84, 0xd5, 0x16, 0x9d, 0xc3, 0x61, 0x43, 0x85, 0x64, 0x05, 0xd7, 0x06, 0x8f, 0xe7, 0x33,
	0xbf, 0x1f, 0xb3, 0xbf, 0xe8, 0x70, 0x3c, 0x08, 0xbc, 0x6b, 0x95, 0xe5, 0xe6, 0x7f, 0x59, 0x4e,
	0xc0, 0x6e, 0xe2, 0xbc, 0xa6, 0xc3, 0x68, 0x75, 0xa0, 0x26, 0xce, 0x64, 0x94, 0xd0, 0x5c, 0x77,
	0x39, 0xc1, 0x36, 0x93, 0x57, 0x34, 0x57, 0xd3, 0xfb, 0xd6, 0x3c, 0x3c, 0xbd, 0xf9, 0x6f, 0x03,
	0xac, 0xcf, 0x65, 0x1a, 0xa3, 0x8f, 0x30, 0x5d, 0x50, 0xc1, 0x56, 0xdb, 0x90, 0xa5, 0x17, 0x8d,
	0x24, 0x04, 0x9d, 0x0c, 0x1d, 0xee, 0x5f, 0xbc, 0xd3, 0x7f, 0xd0, 0x21, 0xbd, 0x77, 0x80, 0x3e,
	0xc0, 0x34, 0xa4, 0x3c, 0xd9, 0xbb, 0x0a, 0x68, 0x50, 0xee, 0xb0, 0xdd, 0xe9, 0x7d, 0x73, 0xde,
	0xc1, 0xe5, 0xbb, 0x5f, 0x6f, 0x53, 0x56, 0xdd, 0xd6, 0x4b, 0x9f, 0x14, 0xeb, 0xe0, 0x76, 0x5b,
	0x52, 0xd1, 0xbf, 0x8a, 0x55, 0xbc, 0x14, 0x8c, 0x04, 0xdd, 0x31, 0xfd, 0x7c, 0x96, 0xdd, 0xc3,
	0x79, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x9a, 0x77, 0x05, 0x52, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FpgaClient is the client API for Fpga service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FpgaClient interface {
	VerifySig4Vscc(ctx context.Context, in *VsccEnvelope, opts ...grpc.CallOption) (*VsccResponse, error)
	SendBlock4Mvcc(ctx context.Context, in *Block4Mvcc, opts ...grpc.CallOption) (*MvccResponse, error)
}

type fpgaClient struct {
	cc *grpc.ClientConn
}

func NewFpgaClient(cc *grpc.ClientConn) FpgaClient {
	return &fpgaClient{cc}
}

func (c *fpgaClient) VerifySig4Vscc(ctx context.Context, in *VsccEnvelope, opts ...grpc.CallOption) (*VsccResponse, error) {
	out := new(VsccResponse)
	err := c.cc.Invoke(ctx, "/protos.Fpga/VerifySig4vscc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fpgaClient) SendBlock4Mvcc(ctx context.Context, in *Block4Mvcc, opts ...grpc.CallOption) (*MvccResponse, error) {
	out := new(MvccResponse)
	err := c.cc.Invoke(ctx, "/protos.Fpga/SendBlock4mvcc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FpgaServer is the server API for Fpga service.
type FpgaServer interface {
	VerifySig4Vscc(context.Context, *VsccEnvelope) (*VsccResponse, error)
	SendBlock4Mvcc(context.Context, *Block4Mvcc) (*MvccResponse, error)
}

func RegisterFpgaServer(s *grpc.Server, srv FpgaServer) {
	s.RegisterService(&_Fpga_serviceDesc, srv)
}

func _Fpga_VerifySig4Vscc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VsccEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FpgaServer).VerifySig4Vscc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Fpga/VerifySig4Vscc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FpgaServer).VerifySig4Vscc(ctx, req.(*VsccEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fpga_SendBlock4Mvcc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block4Mvcc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FpgaServer).SendBlock4Mvcc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Fpga/SendBlock4Mvcc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FpgaServer).SendBlock4Mvcc(ctx, req.(*Block4Mvcc))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fpga_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Fpga",
	HandlerType: (*FpgaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifySig4vscc",
			Handler:    _Fpga_VerifySig4Vscc_Handler,
		},
		{
			MethodName: "SendBlock4mvcc",
			Handler:    _Fpga_SendBlock4Mvcc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fpga/fpga.proto",
}
